## Loading Data for Modeling

In [1]:
import sys
import imp 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

sys.path.append('../data_processing_code/')

### Loading Experiment 1 data

In [2]:
import get_data
imp.reload(get_data)
from get_data import get_data

In [3]:
dftmp = pd.read_csv('../data/participant_table_exp1.csv')
data = get_data(dftmp)

pain task excluded:12
rew task excluded:9
has both: 71
pain only:6
rew only:9
subj X task:157
subjs:86
(180, 157)
(180, 157)
(180, 157)
(180, 157)


In [4]:
len(data['MID_all_unique'])

86

In [5]:
data['MID_all_unique'][0:5]

['cb100', 'cb101', 'cb103', 'cb105', 'cb107']

In [6]:
data['STAI_nonscaled']

array([60, 25, 74, 62, 61, 66, 34, 57, 55, 66, 63, 50, 51, 58, 38, 48, 24,
       62, 63, 62, 42, 40, 49, 49, 53, 42, 50, 31, 57, 61, 49, 56, 51, 33,
       52, 56, 63, 22, 63, 70, 59, 48, 44, 36, 35, 26, 34, 33, 35, 29, 38,
       31, 34, 32, 42, 49, 27, 44, 25, 42, 64, 20, 23, 59, 32, 27, 25, 58,
       29, 22, 37, 60, 25, 74, 62, 61, 66, 34, 57, 55, 66, 63, 50, 51, 58,
       38, 48, 24, 62, 63, 62, 42, 40, 49, 49, 53, 42, 50, 31, 57, 61, 49,
       56, 51, 33, 52, 56, 63, 22, 63, 70, 59, 48, 44, 36, 35, 26, 34, 33,
       35, 29, 38, 31, 34, 32, 42, 49, 27, 44, 25, 42, 64, 20, 23, 59, 32,
       27, 25, 58, 29, 22, 37, 28, 47, 62, 34, 64, 48, 73, 64, 21, 41, 60,
       48, 20, 50, 62])

In [7]:
data['Bi1item_w_j_scaled_all_unique']

array([ 0.14755804, -0.95709872,  2.26531074,  1.43919799,  1.35177145,
        1.50767057, -1.19398334,  0.3544542 , -0.87226611,  0.41941912,
        0.74939338, -0.50282119,  1.75282067, -0.05899039, -0.90948916,
       -0.98627509, -1.4326846 ,  1.70081521,  1.4013291 ,  0.58111659,
       -0.8453864 , -0.30890789,  0.37945351,  0.0118929 ,  1.29360302,
       -0.4265411 , -0.25434775, -0.80550727,  1.04393912,  1.43690884,
        0.66425017, -0.56126892,  0.19483674, -0.77689611, -0.29200188,
        1.97956206,  2.13902264, -1.10610059,  1.58339688,  1.75518496,
       -0.37319643, -0.04607938, -0.01699019, -0.74608116, -1.0693396 ,
       -1.13634699, -1.15640149, -1.15123364, -0.21043034, -1.14501248,
       -0.71669323, -0.19487028, -0.35051931, -0.44158464, -0.11564757,
       -0.35722452, -0.77463108, -0.36726959, -0.63635009, -0.97250678,
        1.03341479, -0.98311704, -0.96913988,  1.27214139, -0.0365546 ,
       -0.91620724, -1.29125694,  0.72494687, -0.48118133, -1.25

### Loading Experiment 2 data

In [27]:
import get_data
imp.reload(get_data)
from get_data import get_data_online

In [28]:
dftmp = pd.read_csv('../data/participant_table_exp2.csv',index_col=0)
data_online = get_data_online(dftmp)

subj X task:294
subjs:147
(180, 294)
(180, 294)
(180, 294)
(180, 294)


/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1205: RuntimeWarning: Mean of empty slice
  mean_ = np.nanmean(X, axis)
/Users/chrisgagne/anaconda3/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1628: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1212: RuntimeWarning: Mean of empty slice
  mean_1 = np.nanmean(Xr, axis=0)
/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1219: RuntimeWarning: Mean of empty slice
  mean_2 = np.nanmean(Xr, axis=0)
/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1088: RuntimeWarning: Mean of empty slice
  PSWQ_scaled[np.isnan(PSWQ_scaled)]=np.nanmean(PSWQ_scaled) # impute mean
/Users/chrisgagne/s

In [29]:
data_online['MID_all_unique']

['mturk0',
 'mturk1',
 'mturk10',
 'mturk100',
 'mturk101',
 'mturk102',
 'mturk103',
 'mturk104',
 'mturk105',
 'mturk106',
 'mturk107',
 'mturk108',
 'mturk109',
 'mturk11',
 'mturk110',
 'mturk111',
 'mturk112',
 'mturk113',
 'mturk114',
 'mturk115',
 'mturk116',
 'mturk117',
 'mturk118',
 'mturk119',
 'mturk12',
 'mturk120',
 'mturk121',
 'mturk122',
 'mturk123',
 'mturk124',
 'mturk125',
 'mturk126',
 'mturk127',
 'mturk128',
 'mturk129',
 'mturk13',
 'mturk130',
 'mturk131',
 'mturk132',
 'mturk133',
 'mturk134',
 'mturk135',
 'mturk136',
 'mturk137',
 'mturk138',
 'mturk139',
 'mturk14',
 'mturk140',
 'mturk141',
 'mturk142',
 'mturk143',
 'mturk144',
 'mturk145',
 'mturk146',
 'mturk15',
 'mturk16',
 'mturk17',
 'mturk18',
 'mturk19',
 'mturk2',
 'mturk20',
 'mturk21',
 'mturk22',
 'mturk23',
 'mturk24',
 'mturk25',
 'mturk26',
 'mturk27',
 'mturk28',
 'mturk29',
 'mturk3',
 'mturk30',
 'mturk31',
 'mturk32',
 'mturk33',
 'mturk34',
 'mturk35',
 'mturk36',
 'mturk37',
 'mturk38

In [30]:
sel = np.where((data_online['stabvol'][0,:]==-1)&(data_online['rewpain'][0,:]==1))[0]

m0=data_online['mag_0_c'][:,sel]
m0
#plt.plot(m0[0:10])

array([[0.99, 0.99, 0.99, ..., 0.99, 0.99, 0.99],
       [0.96, 0.96, 0.96, ..., 0.96, 0.96, 0.96],
       [0.58, 0.58, 0.58, ..., 0.58, 0.58, 0.58],
       ...,
       [0.65, 0.65, 0.65, ..., 0.65, 0.65, 0.65],
       [0.66, 0.66, 0.66, ..., 0.66, 0.66, 0.66],
       [0.35, 0.35, 0.35, ..., 0.35, 0.35, 0.35]])

In [31]:
data_online['STAI_scaled']

array([-1.4296825 , -0.72391013, -0.01813776,  0.373958  , -0.95916759,
       -1.35126335, -0.72391013, -1.50810165,  1.47182612, -0.01813776,
        0.76605376, -0.80232928, -1.82177826,  1.07973036, -1.19442504,
        1.62866443, -0.41023352,  0.06028139, -0.33181437, -0.64549098,
       -0.95916759,  1.00131121,  0.60921545, -1.5865208 , -1.35126335,
        0.06028139,  0.84447291, -0.01813776, -0.25339522, -0.48865267,
       -0.80232928,  1.55024528,  1.23656867,  1.39340697, -0.41023352,
       -1.66493995, -1.35126335, -1.82177826, -1.11600589,  0.5307963 ,
       -1.5865208 , -0.17497607,  1.07973036, -1.35126335, -1.50810165,
       -0.48865267,  1.31498782,  2.09917934, -0.25339522,  0.21711969,
        1.55024528, -0.41023352,  0.76605376,  0.373958  ,  0.6876346 ,
        0.373958  ,  0.06028139, -0.48865267, -0.64549098,  0.06028139,
        1.00131121, -0.17497607,  1.00131121,  0.76605376,  0.84447291,
        0.06028139,  1.07973036, -1.19442504,  1.00131121, -0.80

In [32]:
# plt.scatter(data_online['STAI_scaled_all_unique'],
#             data_online['Bi1item_w_j_scaled_all_unique'])