## Loading Data for Modeling

In [18]:
import sys
import imp 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

sys.path.append('../data_processing_code/')

### Loading Experiment 1 data

In [19]:
import get_data
imp.reload(get_data)
from get_data import get_data

In [20]:
dftmp = pd.read_csv('../data/participant_table_exp1.csv')
data = get_data(dftmp)

pain task excluded:12
rew task excluded:9
has both: 71
pain only:6
rew only:9
subj X task:157
subjs:86
(180, 157)
(180, 157)
(180, 157)
(180, 157)


In [21]:
len(data['MID_all_unique'])

86

In [22]:
data['MID_all_unique'][0:5]

['cb100', 'cb101', 'cb103', 'cb105', 'cb107']

In [23]:
data['STAI_nonscaled']

array([60, 25, 74, 62, 61, 66, 34, 57, 55, 66, 63, 50, 51, 58, 38, 48, 24,
       62, 63, 62, 42, 40, 49, 49, 53, 42, 50, 31, 57, 61, 49, 56, 51, 33,
       52, 56, 63, 22, 63, 70, 59, 48, 44, 36, 35, 26, 34, 33, 35, 29, 38,
       31, 34, 32, 42, 49, 27, 44, 25, 42, 64, 20, 23, 59, 32, 27, 25, 58,
       29, 22, 37, 60, 25, 74, 62, 61, 66, 34, 57, 55, 66, 63, 50, 51, 58,
       38, 48, 24, 62, 63, 62, 42, 40, 49, 49, 53, 42, 50, 31, 57, 61, 49,
       56, 51, 33, 52, 56, 63, 22, 63, 70, 59, 48, 44, 36, 35, 26, 34, 33,
       35, 29, 38, 31, 34, 32, 42, 49, 27, 44, 25, 42, 64, 20, 23, 59, 32,
       27, 25, 58, 29, 22, 37, 28, 47, 62, 34, 64, 48, 73, 64, 21, 41, 60,
       48, 20, 50, 62])

In [24]:
data['Bi1item_w_j_scaled_all_unique']

array([ 0.14755804, -0.95709872,  2.26531074,  1.43919799,  1.35177145,
        1.50767057, -1.19398334,  0.3544542 , -0.87226611,  0.41941912,
        0.74939338, -0.50282119,  1.75282067, -0.05899039, -0.90948916,
       -0.98627509, -1.4326846 ,  1.70081521,  1.4013291 ,  0.58111659,
       -0.8453864 , -0.30890789,  0.37945351,  0.0118929 ,  1.29360302,
       -0.4265411 , -0.25434775, -0.80550727,  1.04393912,  1.43690884,
        0.66425017, -0.56126892,  0.19483674, -0.77689611, -0.29200188,
        1.97956206,  2.13902264, -1.10610059,  1.58339688,  1.75518496,
       -0.37319643, -0.04607938, -0.01699019, -0.74608116, -1.0693396 ,
       -1.13634699, -1.15640149, -1.15123364, -0.21043034, -1.14501248,
       -0.71669323, -0.19487028, -0.35051931, -0.44158464, -0.11564757,
       -0.35722452, -0.77463108, -0.36726959, -0.63635009, -0.97250678,
        1.03341479, -0.98311704, -0.96913988,  1.27214139, -0.0365546 ,
       -0.91620724, -1.29125694,  0.72494687, -0.48118133, -1.25

### Loading Experiment 2 data

In [25]:
import get_data
imp.reload(get_data)
from get_data import get_data_online

In [26]:
dftmp = pd.read_csv('../data/participant_table_exp2.csv',index_col=0)
data_online = get_data_online(dftmp)

subj X task:294
subjs:147
(180, 294)
(180, 294)
(180, 294)
(180, 294)


/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1201: RuntimeWarning: Mean of empty slice
  mean_ = np.nanmean(X, axis)
/Users/chrisgagne/anaconda3/envs/pymc3_3.6/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1667: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1208: RuntimeWarning: Mean of empty slice
  mean_1 = np.nanmean(Xr, axis=0)
/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1215: RuntimeWarning: Mean of empty slice
  mean_2 = np.nanmean(Xr, axis=0)
/Users/chrisgagne/synced_folders/bishop_lab_projects/volatility_paper_elife_submission/data_processing_code/get_data.py:1084: RuntimeWarning: Mean of empty slice
  PSWQ_scaled[np.isnan(PSWQ_scaled)]=np.nanmean(PSWQ_scaled) # impute mean
/Use

In [27]:
data_online['MID_all_unique']

['3259',
 '3337',
 '3364',
 '3394',
 '3502',
 '3544',
 '3562',
 '3571',
 '3715',
 '3778',
 '3838',
 '3850',
 '3925',
 '3976',
 '4174',
 '4300',
 '4423',
 '4438',
 '4573',
 '4591',
 '4603',
 '4627',
 '4636',
 '4846',
 '4975',
 '5131',
 '5263',
 '5377',
 '5533',
 '5584',
 '5620',
 '5641',
 '5863',
 '6199',
 '6265',
 '6529',
 '6583',
 '6637',
 '6697',
 '6733',
 '7006',
 '7165',
 '7210',
 '7231',
 '7381',
 '7429',
 '7444',
 '7495',
 '7726',
 '7771',
 '7867',
 'A10DEO061A6L3O',
 'A110KENBXU7SUJ',
 'A11UQWFUDNIHIL',
 'A14I3K8UN3612X',
 'A1640H4RXH8NZE',
 'A16HSMUJ7C7QA7',
 'A18T67NDI2JK5Y',
 'A195KL2GMUGRF3',
 'A1BI9SFVFNAUWV',
 'A1C59M3HPCO503',
 'A1CH3TODZNQCES',
 'A1EQ2HDHF2WWSY',
 'A1F34ZP6YNI98F',
 'A1FQGVP8SX5WE2',
 'A1JV64BL3WCK0G',
 'A1M9H7WED4RUD5',
 'A1MB3A5MC58LK6',
 'A1N4AZ1QXPOPXH',
 'A1P3Z24Y6GRNVA',
 'A1P8WL2QGA7WHE',
 'A1PUHCEBSOWETV',
 'A1SL65Z68BK1UT',
 'A1SRF7085UM3HI',
 'A1UI059YV3XH73',
 'A1UR6G66USZR5R',
 'A1UXYMMASB2X1Q',
 'A1WISFBL3J5Z12',
 'A1WL3NZ50YEOWP',
 'A1WR6M7

In [28]:
sel = np.where((data_online['stabvol'][0,:]==-1)&(data_online['rewpain'][0,:]==1))[0]

m0=data_online['mag_0_c'][:,sel]
m0
#plt.plot(m0[0:10])

array([[0.99, 0.99, 0.99, ..., 0.99, 0.99, 0.01],
       [0.96, 0.96, 0.96, ..., 0.96, 0.96, 0.12],
       [0.58, 0.58, 0.58, ..., 0.58, 0.58, 0.9 ],
       ...,
       [0.65, 0.65, 0.65, ..., 0.65, 0.65, 0.61],
       [0.66, 0.66, 0.66, ..., 0.66, 0.66, 0.72],
       [0.35, 0.35, 0.35, ..., 0.35, 0.35, 0.4 ]])

In [29]:
data_online['STAI_scaled']

array([-1.4296825 , -0.72391013,  0.06028139,  1.39340697, -0.09655691,
       -0.64549098, -0.33181437,  0.21711969, -0.72391013, -0.56707183,
       -0.01813776,  1.07973036, -1.35126335, -1.66493995,  1.31498782,
        0.6876346 ,  0.373958  ,  0.06028139, -0.48865267, -0.64549098,
        1.00131121, -0.17497607,  1.00131121,  0.76605376,  0.84447291,
        0.06028139,  1.07973036, -1.19442504,  1.00131121, -0.80232928,
       -0.09655691, -0.56707183, -0.48865267, -0.48865267, -0.64549098,
       -0.25339522,  0.45237715, -0.01813776, -1.03758674,  0.60921545,
        1.47182612,  0.6876346 ,  0.21711969,  0.373958  ,  0.45237715,
        0.21711969,  0.21711969,  0.60921545,  1.00131121, -1.35126335,
        1.47182612,  1.78550273,  1.07973036, -0.41023352,  2.56969425,
        0.60921545, -0.80232928, -0.25339522, -1.74335911, -0.17497607,
        0.76605376,  0.84447291, -1.50810165, -0.09655691, -0.56707183,
       -0.25339522, -1.82177826, -0.48865267,  1.23656867, -1.66