## Loading Data for Modeling

In [45]:
import sys
import imp 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

sys.path.append('../data_processing_code/')

### Loading Experiment 1 data

In [46]:
import get_data
imp.reload(get_data)
from get_data import get_data

In [47]:
dftmp = pd.read_csv('../data/participant_table_exp1.csv')
data = get_data(dftmp)

pain task excluded:12
rew task excluded:9
has both: 71
pain only:6
rew only:9
subj X task:157
subjs:86
(180, 157)
(180, 157)
(180, 157)
(180, 157)


In [48]:
len(data['MID_all_unique'])

86

In [49]:
data['MID_all_unique'][0:5]

['cb100', 'cb101', 'cb103', 'cb105', 'cb107']

In [50]:
data['STAI_nonscaled']

array([60., 25., 74., 62., 61., 66., 34., 57., 55., 66., 63., 50., 51.,
       58., 38., 48., 24., 62., 63., 62., 42., 40., 49., 49., 53., 42.,
       50., 31., 57., 61., 49., 56., 51., 33., 52., 56., 63., 22., 63.,
       70., 59., 48., 44., 36., 35., 26., 34., 33., 35., 29., 38., 31.,
       34., 32., 42., 49., 27., 44., 25., 42., 64., 20., 23., 59., 32.,
       27., 25., 58., 29., 22., 37., 60., 25., 74., 62., 61., 66., 34.,
       57., 55., 66., 63., 50., 51., 58., 38., 48., 24., 62., 63., 62.,
       42., 40., 49., 49., 53., 42., 50., 31., 57., 61., 49., 56., 51.,
       33., 52., 56., 63., 22., 63., 70., 59., 48., 44., 36., 35., 26.,
       34., 33., 35., 29., 38., 31., 34., 32., 42., 49., 27., 44., 25.,
       42., 64., 20., 23., 59., 32., 27., 25., 58., 29., 22., 37., 28.,
       47., 62., 34., 64., 48., 73., 64., 21., 41., 60., 48., 20., 50.,
       62.])

In [51]:
data['Bi1item_w_j_scaled_all_unique']

array([ 0.14755804, -0.95709872,  2.26531074,  1.43919799,  1.35177145,
        1.50767057, -1.19398334,  0.3544542 , -0.87226611,  0.41941912,
        0.74939338, -0.50282119,  1.75282067, -0.05899039, -0.90948916,
       -0.98627509, -1.4326846 ,  1.70081521,  1.4013291 ,  0.58111659,
       -0.8453864 , -0.30890789,  0.37945351,  0.0118929 ,  1.29360302,
       -0.4265411 , -0.25434775, -0.80550727,  1.04393912,  1.43690884,
        0.66425017, -0.56126892,  0.19483674, -0.77689611, -0.29200188,
        1.97956206,  2.13902264, -1.10610059,  1.58339688,  1.75518496,
       -0.37319643, -0.04607938, -0.01699019, -0.74608116, -1.0693396 ,
       -1.13634699, -1.15640149, -1.15123364, -0.21043034, -1.14501248,
       -0.71669323, -0.19487028, -0.35051931, -0.44158464, -0.11564757,
       -0.35722452, -0.77463108, -0.36726959, -0.63635009, -0.97250678,
        1.03341479, -0.98311704, -0.96913988,  1.27214139, -0.0365546 ,
       -0.91620724, -1.29125694,  0.72494687, -0.48118133, -1.25

### Loading Experiment 2 data

In [52]:
import get_data
imp.reload(get_data)
from get_data import get_data_online

In [53]:
dftmp = pd.read_csv('../data/participant_table_exp2.csv',index_col=0)
data_online = get_data_online(dftmp)

subj X task:294
subjs:147
(180, 294)
(180, 294)
(180, 294)
(180, 294)


In [54]:
data_online['Bi1item_w_j_scaled_all_unique']

array([-1.00025022, -1.19946744, -0.53672669,  1.41121712, -0.29582416,
       -0.23185864,  0.42176731,  0.68375913, -0.82893223, -0.80898426,
        0.91926769,  1.74305704, -0.81580377, -1.29661043,  1.08838735,
        0.71558606,  0.48042643, -0.25095134, -0.59839733, -1.09433368,
        0.22895317, -0.67136804,  1.08232784,  0.07950893,  1.33441136,
       -0.59427074,  0.14718968, -0.7694283 ,  1.55458743, -0.38102946,
       -0.19772393, -0.71869382,  0.10138506, -1.11834739, -0.36898771,
       -0.19916131,  0.24790473,  0.32469091, -0.12148703,  0.65550134,
        0.22762506,  1.49387336,  0.6139124 , -0.05507091,  2.91265122,
        0.03534353,  0.76968686,  0.29903459,  1.22842856, -0.72290388,
        3.21669483,  1.35777685,  0.71485646, -1.03407448,  2.93509741,
        0.17658657, -0.64553953, -0.2698443 , -1.15595836, -0.93131291,
        0.04131904,  1.51970572, -1.08182534, -0.18057033, -0.8020161 ,
       -0.78360174, -1.41558055, -0.80995949,  0.45055741, -1.13

In [55]:
sel = np.where((data_online['stabvol'][0,:]==-1)&(data_online['rewpain'][0,:]==1))[0]

m0=data_online['mag_0_c'][:,sel]
m0
#plt.plot(m0[0:10])

array([[0.99, 0.99, 0.99, ..., 0.99, 0.99, 0.01],
       [0.96, 0.96, 0.96, ..., 0.96, 0.96, 0.12],
       [0.58, 0.58, 0.58, ..., 0.58, 0.58, 0.9 ],
       ...,
       [0.65, 0.65, 0.65, ..., 0.65, 0.65, 0.61],
       [0.66, 0.66, 0.66, ..., 0.66, 0.66, 0.72],
       [0.35, 0.35, 0.35, ..., 0.35, 0.35, 0.4 ]])